version: '3.3'
services:
  db:
    image: ${MYSQL_IMAGE}
    container_name: db_container
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db_config:/etc/mysql
    ports:      
      - ${MYSQL_PORT}:3306
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}

  wordpress:
    depends_on:
      - db
    image: ${WORKPRESS_IMAGE}
    container_name: wp_container
    volumes:
      - ./wp_data:/var/www/html
    ports:
      - ${WORDPRESS_PORT}:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
